// Products data with categories
const products = [
  {
    id: 1,
    name: 'Dental Bridge Poster - Dentist Clinic',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print without frame. This Dental patient education poster is designed to educate patients on how to maintain good oral hygiene.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/41y1HiZrYtL.jpg',
    image1: 'https://m.media-amazon.com/images/I/41y1HiZrYtL.jpg',
    image2: 'https://i.postimg.cc/MGvyH6cJ/4-DDB8-C46-F251-43-D4-9-A67-357-BCC8-CF379.png'
  },
  {
    id: 2,
    name: 'Dental poster teeth crowns patient education',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print without frame. Patient education poster for dental clinics.',
    size: '12x18 inch',
    color: 'Multi',
    tag: 'Trendy',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/712dscQLWtL.jpg',
    image1: 'https://m.media-amazon.com/images/I/712dscQLWtL.jpg',
    image2: 'https://i.postimg.cc/xdhLbwHJ/6-A38-DA7-F-EA83-42-AB-961-B-24-B69293-B5-C1.png'
  },
  {
    id: 3,
    name: 'Healthy Mouth Dental poster',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Patient education for maintaining oral hygiene.',
    size: '12x18 inch',
    color: 'Multi',
    tag: 'Trendy',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71vOFtvMC0L.jpg',
    image1: 'https://m.media-amazon.com/images/I/71vOFtvMC0L.jpg',
    image2: 'https://i.postimg.cc/t4r39Z4z/A2-BF686-F-C285-4693-B36-A-E7048-DE63483.png'
  },
  {
    id: 4,
    name: 'Dental patient education poster caries awareness',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Caries awareness education poster.',
    size: '12x18 inch',
    color: 'Multi',
    tag: 'Trendy',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71YBGJTvr3L.jpg',
    image1: 'https://m.media-amazon.com/images/I/71YBGJTvr3L.jpg',
    image2: 'https://i.postimg.cc/L6mRph75/11.png'
  },
  {
    id: 5,
    name: 'Dental floss poster for dental clinic',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Dental floss importance poster.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 999,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71-khyA-wfL.jpg',
    image1: 'https://m.media-amazon.com/images/I/71-khyA-wfL.jpg',
    image2: 'https://i.postimg.cc/FR8RpSVD/51.png'
  },
  {
    id: 6,
    name: 'Dental implant sinus lift poster',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Dental implant procedure education.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 999,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71yF020qETL.jpg',
    image1: 'https://m.media-amazon.com/images/I/71yF020qETL.jpg',
    image2: 'https://i.postimg.cc/4NtK8WMt/52.png'
  },
  {
    id: 7,
    name: 'Dental poster oral health awareness',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Oral health awareness poster.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 999,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/514kHm7hMOL.jpg',
    image1: 'https://m.media-amazon.com/images/I/514kHm7hMOL.jpg',
    image2: 'https://i.postimg.cc/nrmLPLdZ/53.png'
  },
  {
    id: 8,
    name: 'Dental poster caries oral health awareness',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Caries and oral health awareness.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/61bR-8EI4gL.jpg',
    image1: 'https://m.media-amazon.com/images/I/61bR-8EI4gL.jpg',
    image2: 'https://i.postimg.cc/cCPs7NZj/54.png'
  },
  {
    id: 9,
    name: 'Teeth whitening Dental patient education',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Teeth whitening education poster.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71AJlCafJRL.jpg',
    image1: 'https://m.media-amazon.com/images/I/71AJlCafJRL.jpg',
    image2: 'https://i.postimg.cc/4xgYjzk0/55.png'
  },
  {
    id: 10,
    name: 'OHF caries patient education Dental poster',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. OHF caries education.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/610lvU3FNnL.jpg',
    image1: 'https://m.media-amazon.com/images/I/610lvU3FNnL.jpg',
    image2: ''
  }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = products;
}// Products data with categories
const products = [
  {
    id: 1,
    name: 'Dental Anatomy Poster',
    category: 'Dental',
    price: 299,
    description: 'Detailed human dental anatomy and structure',
    size: 'A3',
    color: 'Color',
    tag: 'educational',
    brand: 'StatusRing',
    stock: 50,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Dental+Anatomy',
    image1: '',
    image2: ''
  },
  {
    id: 2,
    name: 'Teeth Cleaning Chart',
    category: 'Dental',
    price: 199,
    description: 'Proper teeth brushing and cleaning techniques',
    size: 'A4',
    color: 'Color',
    tag: 'guide',
    brand: 'StatusRing',
    stock: 100,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Teeth+Cleaning',
    image1: '',
    image2: ''
  },
  {
    id: 3,
    name: 'Orthodontics Guide',
    category: 'Dental',
    price: 399,
    description: 'Complete guide to orthodontic treatments',
    size: 'A2',
    color: 'Color',
    tag: 'specialist',
    brand: 'StatusRing',
    stock: 30,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Orthodontics',
    image1: '',
    image2: ''
  },
  {
    id: 4,
    name: 'Skeletal System Chart',
    category: 'Medical',
    price: 349,
    description: 'Complete human skeletal system with labels',
    size: 'A3',
    color: 'Color',
    tag: 'anatomy',
    brand: 'StatusRing',
    stock: 40,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Skeletal+System',
    image1: '',
    image2: ''
  },
  {
    id: 5,
    name: 'Human Organs Poster',
    category: 'Medical',
    price: 349,
    description: 'Detailed diagram of human organ systems',
    size: 'A3',
    color: 'Color',
    tag: 'anatomy',
    brand: 'StatusRing',
    stock: 45,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Human+Organs',
    image1: '',
    image2: ''
  },
  {
    id: 6,
    name: 'First Aid Guide',
    category: 'Medical',
    price: 249,
    description: 'Essential first aid procedures and tips',
    size: 'A4',
    color: 'Color',
    tag: 'guide',
    brand: 'StatusRing',
    stock: 60,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=First+Aid',
    image1: '',
    image2: ''
  },
  {
    id: 7,
    name: 'Root Canal Procedure',
    category: 'Dental',
    price: 449,
    description: 'Step-by-step root canal treatment procedure',
    size: 'A2',
    color: 'Color',
    tag: 'specialist',
    brand: 'StatusRing',
    stock: 25,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Root+Canal',
    image1: '',
    image2: ''
  },
  {
    id: 8,
    name: 'Blood Circulation Chart',
    category: 'Medical',
    price: 379,
    description: 'Detailed diagram of human blood circulation system',
    size: 'A3',
    color: 'Color',
    tag: 'anatomy',
    brand: 'StatusRing',
    stock: 35,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Blood+Circulation',
    image1: '',
    image2: ''
  }
];
