// Products data with categories
var products = [
  {
    id: 1,
    name: 'Dental Bridge Poster - Dentist Clinic',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print without frame. This Dental patient education poster is designed to educate patients on how to maintain good oral hygiene.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/41y1HiZrYtL.jpg',
    image1: 'https://m.media-amazon.com/images/I/41y1HiZrYtL.jpg',
    image2: 'https://i.postimg.cc/MGvyH6cJ/4-DDB8-C46-F251-43-D4-9-A67-357-BCC8-CF379.png'
  },
  {
    id: 2,
    name: 'Dental poster teeth crowns patient education',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print without frame. Patient education poster for dental clinics.',
    size: '12x18 inch',
    color: 'Multi',
    tag: 'Trendy',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/712dscQLWtL.jpg',
    image1: 'https://m.media-amazon.com/images/I/712dscQLWtL.jpg',
    image2: 'https://i.postimg.cc/xdhLbwHJ/6-A38-DA7-F-EA83-42-AB-961-B-24-B69293-B5-C1.png'
  },
  {
    id: 3,
    name: 'Healthy Mouth Dental poster',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Patient education for maintaining oral hygiene.',
    size: '12x18 inch',
    color: 'Multi',
    tag: 'Trendy',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71vOFtvMC0L.jpg',
    image1: 'https://m.media-amazon.com/images/I/71vOFtvMC0L.jpg',
    image2: 'https://i.postimg.cc/t4r39Z4z/A2-BF686-F-C285-4693-B36-A-E7048-DE63483.png'
  },
  {
    id: 4,
    name: 'Dental patient education poster caries awareness',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Caries awareness education poster.',
    size: '12x18 inch',
    color: 'Multi',
    tag: 'Trendy',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71YBGJTvr3L.jpg',
    image1: 'https://m.media-amazon.com/images/I/71YBGJTvr3L.jpg',
    image2: 'https://i.postimg.cc/L6mRph75/11.png'
  },
  {
    id: 5,
    name: 'Dental floss poster for dental clinic',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Dental floss importance poster.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 999,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71-khyA-wfL.jpg',
    image1: 'https://m.media-amazon.com/images/I/71-khyA-wfL.jpg',
    image2: 'https://i.postimg.cc/FR8RpSVD/51.png'
  },
  {
    id: 6,
    name: 'Dental implant sinus lift poster',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Dental implant procedure education.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 999,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71yF020qETL.jpg',
    image1: 'https://m.media-amazon.com/images/I/71yF020qETL.jpg',
    image2: 'https://i.postimg.cc/4NtK8WMt/52.png'
  },
  {
    id: 7,
    name: 'Dental poster oral health awareness',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Oral health awareness poster.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 999,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/514kHm7hMOL.jpg',
    image1: 'https://m.media-amazon.com/images/I/514kHm7hMOL.jpg',
    image2: 'https://i.postimg.cc/nrmLPLdZ/53.png'
  },
  {
    id: 8,
    name: 'Dental poster caries oral health awareness',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Caries and oral health awareness.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/61bR-8EI4gL.jpg',
    image1: 'https://m.media-amazon.com/images/I/61bR-8EI4gL.jpg',
    image2: 'https://i.postimg.cc/cCPs7NZj/54.png'
  },
  {
    id: 9,
    name: 'Teeth whitening Dental patient education',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Teeth whitening education poster.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71AJlCafJRL.jpg',
    image1: 'https://m.media-amazon.com/images/I/71AJlCafJRL.jpg',
    image2: 'https://i.postimg.cc/4xgYjzk0/55.png'
  },
  {
    id: 10,
    name: 'OHF caries patient education Dental poster',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. OHF caries education.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/610lvU3FNnL.jpg',
    image1: 'https://m.media-amazon.com/images/I/610lvU3FNnL.jpg',
    image2: ''
  }
];

// Additional products (IDs 11-20)
var productsExtra = [
  {
    id: 11,
    name: 'Oral health first patient education Dental poster',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Oral health awareness.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/61kxt0R8Q9L.jpg',
    image1: 'https://m.media-amazon.com/images/I/61kxt0R8Q9L.jpg',
    image2: ''
  },
  {
    id: 12,
    name: 'OHF swelling patient education Dental poster',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Swelling awareness.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/617ut-9eYdL.jpg',
    image1: 'https://m.media-amazon.com/images/I/617ut-9eYdL.jpg',
    image2: ''
  },
  {
    id: 13,
    name: 'OHF shining patient education Dental poster',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Dental awareness.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/61Ms3+axC+L.jpg',
    image1: 'https://m.media-amazon.com/images/I/61Ms3+axC+L.jpg',
    image2: ''
  },
  {
    id: 14,
    name: 'Dental Poster offer Super Six',
    category: 'Dental Posters',
    price: 1800,
    description: 'Size: 12x18 inches Regular Paper 170 GSM print. Package of 6 posters.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71EAKd7E4GL.jpg',
    image1: 'https://m.media-amazon.com/images/I/71EAKd7E4GL.jpg',
    image2: ''
  },
  {
    id: 15,
    name: 'Fungal infection Poster for patient education',
    category: 'Skin Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Fungal infection awareness.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://i.postimg.cc/rmNgNfbp/Fungal-infection-Poster-for-patiebt-education-withoutframe.png',
    image1: 'https://i.postimg.cc/rmNgNfbp/Fungal-infection-Poster-for-patiebt-education-withoutframe.png',
    image2: ''
  },
  {
    id: 16,
    name: 'Hair Extension poster for salon',
    category: 'Skin Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Hair extension education.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://i.postimg.cc/DZTBG9xD/Hair-Extension-poster-saloon-and-hair-clinic-poster-without-frame-Status-Ring.png',
    image1: 'https://i.postimg.cc/DZTBG9xD/Hair-Extension-poster-saloon-and-hair-clinic-poster-without-frame-Status-Ring.png',
    image2: ''
  },
  {
    id: 17,
    name: 'Skin Care Treatment Poster',
    category: 'Skin Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Skin care awareness.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://i.postimg.cc/JzRrT0G4/Skin-Care-Skin-Treatment-Poster-Without-Frame.png',
    image1: 'https://i.postimg.cc/JzRrT0G4/Skin-Care-Skin-Treatment-Poster-Without-Frame.png',
    image2: ''
  },
  {
    id: 18,
    name: 'Dental poster Package of 3',
    category: 'Dental Posters',
    price: 1350,
    description: 'Size: 12x18 inches high Quality Paper print. Package of 3 posters.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71vHN8y1BiL.jpg',
    image1: 'https://m.media-amazon.com/images/I/71vHN8y1BiL.jpg',
    image2: ''
  },
  {
    id: 19,
    name: 'Package of 6 Posters Dental education',
    category: 'Dental Posters',
    price: 2700,
    description: 'Size: 12x18 inches high Quality Paper print. Package of 6 posters.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://m.media-amazon.com/images/I/71QBYcTaXKL.jpg',
    image1: 'https://m.media-amazon.com/images/I/71QBYcTaXKL.jpg',
    image2: ''
  },
  {
    id: 20,
    name: 'Dental Tooth structure patient education',
    category: 'Dental Posters',
    price: 450,
    description: 'Size: 12x18 inches high Quality Paper print. Tooth structure education.',
    size: '12x18 inch',
    color: 'Multi',
    tag: '',
    brand: 'Status Ring',
    stock: 1000,
    availability: 'Show',
    thumbnail: 'https://i.postimg.cc/KvzQtr5Z/Dental-Tooth-structure-patient-education-morden-style-Dentist-poster-without-frame.png',
    image1: 'https://i.postimg.cc/KvzQtr5Z/Dental-Tooth-structure-patient-education-morden-style-Dentist-poster-without-frame.png',
    image2: ''
  }
];

// Merge extra products into main array
products.push(...productsExtra);

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = products;
}
