// Products data with categories
const products = [
  {
    id: 1,
    name: 'Dental Anatomy Poster',
    category: 'Dental',
    price: 299,
    description: 'Detailed human dental anatomy and structure',
    size: 'A3',
    color: 'Color',
    tag: 'educational',
    brand: 'StatusRing',
    stock: 50,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Dental+Anatomy',
    image1: '',
    image2: ''
  },
  {
    id: 2,
    name: 'Teeth Cleaning Chart',
    category: 'Dental',
    price: 199,
    description: 'Proper teeth brushing and cleaning techniques',
    size: 'A4',
    color: 'Color',
    tag: 'guide',
    brand: 'StatusRing',
    stock: 100,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Teeth+Cleaning',
    image1: '',
    image2: ''
  },
  {
    id: 3,
    name: 'Orthodontics Guide',
    category: 'Dental',
    price: 399,
    description: 'Complete guide to orthodontic treatments',
    size: 'A2',
    color: 'Color',
    tag: 'specialist',
    brand: 'StatusRing',
    stock: 30,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Orthodontics',
    image1: '',
    image2: ''
  },
  {
    id: 4,
    name: 'Skeletal System Chart',
    category: 'Medical',
    price: 349,
    description: 'Complete human skeletal system with labels',
    size: 'A3',
    color: 'Color',
    tag: 'anatomy',
    brand: 'StatusRing',
    stock: 40,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Skeletal+System',
    image1: '',
    image2: ''
  },
  {
    id: 5,
    name: 'Human Organs Poster',
    category: 'Medical',
    price: 349,
    description: 'Detailed diagram of human organ systems',
    size: 'A3',
    color: 'Color',
    tag: 'anatomy',
    brand: 'StatusRing',
    stock: 45,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Human+Organs',
    image1: '',
    image2: ''
  },
  {
    id: 6,
    name: 'First Aid Guide',
    category: 'Medical',
    price: 249,
    description: 'Essential first aid procedures and tips',
    size: 'A4',
    color: 'Color',
    tag: 'guide',
    brand: 'StatusRing',
    stock: 60,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=First+Aid',
    image1: '',
    image2: ''
  },
  {
    id: 7,
    name: 'Root Canal Procedure',
    category: 'Dental',
    price: 449,
    description: 'Step-by-step root canal treatment procedure',
    size: 'A2',
    color: 'Color',
    tag: 'specialist',
    brand: 'StatusRing',
    stock: 25,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Root+Canal',
    image1: '',
    image2: ''
  },
  {
    id: 8,
    name: 'Blood Circulation Chart',
    category: 'Medical',
    price: 379,
    description: 'Detailed diagram of human blood circulation system',
    size: 'A3',
    color: 'Color',
    tag: 'anatomy',
    brand: 'StatusRing',
    stock: 35,
    availability: 'Show',
    thumbnail: 'https://via.placeholder.com/250x200?text=Blood+Circulation',
    image1: '',
    image2: ''
  }
];
